@startuml

actor HR as "HR Advisor"
actor DM as "Department Manager"

rectangle Database

rectangle "HR System" {
    usecase UC1 as "Report Salaries of
    All Employees"
    usecase UC2 as "Report Salaries of
    Employees in a Department"
    usecase UC3 as "Report Salaries of
    Employees in Actor's Department"
    usecase UC4 as "Get salaries by role"
    usecase UC5 as "Add Employee to Database"
    usecase UC6 as "View an Employee Details"
    usecase UC7 as "Update Employee's Details"
    usecase UC8 as "Delete Employee Info"

    HR - UC1
    HR - UC2
    HR - UC4
    HR - UC5
    HR - UC6
    HR - UC7
    HR - UC8

    DM - UC3
    UC4 - Database
}

@enduml